# Generated by Django 5.0 on 2024-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
