# Generated by Django 5.0 on 2024-12-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0005_booking_booking_status_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='baggage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_management.baggage'),
        ),
    ]
